server:
  port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/ewm-main}
    username: ${SPRING_DATASOURCE_USERNAME:main}
    password: ${SPRING_DATASOURCE_PASSWORD:main}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
        dialect: org.hibernate.dialect.PostgreSQLDialect

stats:
  service:
    id: stats-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.netflix: INFO