services:
  stats-db:
    image: postgres:16.1

  ewm-db:
    image: postgres:16.1

  user-db:
    image: postgres:16.1

  request-db:
    image: postgres:16.1

  comment-db:
    image: postgres:16.1

  event-db:
    image: postgres:16.1