CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL
);

-- Индекс для быстрого поиска опубликованных комментариев события
CREATE INDEX IF NOT EXISTS idx_comments_event_status ON comments(event_id, status);

-- Индекс для подсчета количества опубликованных комментариев события
CREATE INDEX IF NOT EXISTS idx_comments_event_status_count ON comments(event_id) WHERE status = 'PUBLISHED';

-- Индекс для поиска комментариев пользователя
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author_id);

-- Индекс для модерации (поиск комментариев в статусе PENDING)
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status) WHERE status = 'PENDING';